fix(azure-deployment): Trigger repull on new catalogue version by upd…
GenomicDataInfrastructure/gdi-userportal-frontend pull request #137
Opened 2024-03-12 15:09 UTC by hcvdwerf

…ating image closes #136

2024-03-12 20:08 UTC, brunopacheco1 commented on .github/workflows/main.yml
> +      - name: Run Trivy vulnerability scanner
important: moving Trivy scanner to this part of the pipeline, will not prevent a vulnerable docker image to be uploaded into the registry. I strongly recommend you execute trivy on a locally build image before pushing it.

2024-03-12 20:13 UTC, brunopacheco1 commented on .github/workflows/main.yml
> +          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
important: I strongly recommend you to revert this change.

`github.sha` is a commit id, which mean you are going to push to the repository always new tags, but `steps.meta.outputs.tags` is a variable filled by `docker/build-push-action` that conveys to tags according to the branch/release strategy we follow, please check their docs.

Besides that, a tag should follow https://semver.org/, but `SHA` is not readable and gives us no context at all.

2024-03-12 20:21 UTC, brunopacheco1 commented on .github/workflows/main.yml
> +          images: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
can you please check an alternative way to redeploy the latest version of a tag? Why is it not happening for the frontend?

2024-03-12 20:21 UTC, brunopacheco1 requested changes
can you please check an alternative way to redeploy the latest version of a tag? Why is it not happening for the frontend?

2024-03-13 12:16 UTC, brunopacheco1 commented on .github/workflows/main.yml
> +          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
I remember having this issue with Amazon and Kubernetes, but we solved it with labels. The tag was still the same, but every new push, we set a label with the commit it. Perhaps Azure also supports it.

In the worse case we can push two tags, the correct one and the commit id tag, but I would recommend you to try first other alternatives. Would you mind checking it?

2024-03-18 15:44 UTC, hcvdwerf commented on .github/workflows/main.yml
> +      - name: Extract second tag
Extract last tag from the list always

2024-03-18 19:34 UTC, brunopacheco1 approved these changes

2024-03-18 19:34 UTC, merged